export { Settings } from './Pendaftaran/Settings';
// export { Monitoring } from './Pendaftaran/Monitoring';
export { DataPendaftaran } from './Pendaftaran/DataPendaftaran';
export { TanggalPendaftaran } from './Pendaftaran/TanggalPendaftaran';
export { Overview } from './Overview/Overview';
export { TableTolokUkur } from './TolokUkur/TableTolokUkur';
export { EditTolokUkur } from './TolokUkur/EditTolokUkur';
export { Setup } from './Setup/Setup';
export { Deployment } from './Deployment/Deployment';
export { Peserta } from './Peserta/Peserta';
export { Monitoring } from './/Monitoring/Monitoring';
export { Laporan } from './Laporan/Laporan';
export { TesMandiri } from './TesMandiri/TesMandiri';
export { TesInteraktif } from './TesInteraktif/TesInteraktif';
export { Pendaftaran } from './Pendaftaran/Pendaftaran';
export { EditModules } from './EditModules/EditModules';
export { EditNorms } from './EditNorms/EditNorms';
export { EditDataPendaftaran } from './EditDataPendaftaran/EditDataPendaftaran';
